# Generated by Django 4.2.5 on 2023-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0004_rename_articulos_articulo_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
