# Generated by Django 4.2.4 on 2023-11-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0005_seccion'),
        ('installed_apps', '0005_seccion_foto'),
    ]

    operations = [
    ]
