# Generated by Django 4.2.5 on 2023-11-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0005_seccion'),
    ]

    operations = [
    ]
