# Generated by Django 4.2.4 on 2023-11-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0006_merge_0005_seccion_0005_seccion_foto'),
        ('installed_apps', '0006_publicacion'),
    ]

    operations = [
    ]
