# Generated by Django 4.2.5 on 2023-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0006_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('superior', 'Parte superior'), ('inferior', 'Parte inferior')], default='superior', max_length=20),
        ),
        migrations.AddField(
            model_name='foto',
            name='genero',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('niño', 'Niño')], default='mujer', max_length=10),
        ),
    ]
