# Generated by Django 4.2.5 on 2023-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installed_apps', '0007_foto_categoria_foto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
